// Hand-picked related topics, shown first on a topic page; getRelatedTopics fills the rest from the category.
// Links run both ways between the question pages (cremation, gambling, ...) and the older topics a reader
// would try next.
export const RELATED = {
  cremation: ["death", "grief", "resurrection", "eternal-life", "heaven", "hell"],
  gambling: ["money", "wealth", "debt", "tithing", "contentment", "giving"],
  "sex-before-marriage": ["purity", "lust", "dating", "marriage", "masturbation", "temptation"],
  cussing: ["gossip", "anger", "self-control", "honesty", "kindness", "sin"],
  lying: ["honesty", "integrity", "truth", "gossip", "justice", "sin"],
  halloween: ["demons", "spiritual-warfare", "idolatry", "holiness", "christmas", "easter"],
  dinosaurs: ["creation", "truth", "wisdom", "faith", "angels", "worship"],
  gluttony: ["self-control", "alcohol", "addiction", "laziness", "fasting", "pride"],
  "eating-pork": ["holiness", "obedience", "fasting", "communion", "freedom", "tattoos"],
  smoking: ["addiction", "alcohol", "self-control", "healing", "mental-health", "stress"],
  masturbation: ["lust", "purity", "self-control", "addiction", "forgiveness", "temptation"],
  death: ["cremation"],
  grief: ["cremation"],
  heaven: ["cremation"],
  resurrection: ["cremation"],
  money: ["gambling"],
  wealth: ["gambling"],
  debt: ["gambling"],
  lust: ["sex-before-marriage", "masturbation"],
  purity: ["sex-before-marriage", "masturbation"],
  dating: ["sex-before-marriage"],
  marriage: ["sex-before-marriage"],
  honesty: ["lying"],
  integrity: ["lying"],
  truth: ["lying"],
  gossip: ["lying", "cussing"],
  anger: ["cussing"],
  addiction: ["smoking", "gluttony", "masturbation"],
  alcohol: ["smoking", "gluttony"],
  "self-control": ["gluttony", "smoking", "cussing", "masturbation"],
  demons: ["halloween"],
  "spiritual-warfare": ["halloween"],
  idolatry: ["halloween"],
  creation: ["dinosaurs"],
  tattoos: ["eating-pork"],
  holiness: ["eating-pork"],
  fasting: ["gluttony", "eating-pork"],
  laziness: ["gluttony"],
  temptation: ["masturbation", "smoking"],
  "mental-health": ["smoking"],
};
