/**
 * Words and phrases with a /words/<slug> page. `forms` are matched in the KJV (case-insensitive, whole words);
 * `web` overrides them for the World English Bible when its wording differs. The first form is the headline word.
 * kind: word (headline = the exact first form) | phrase (headline = all forms together) | name.
 * cases: show the capitalization split (God / god / GOD).
 * topic: the /verses/<topic> page this word belongs with (defaults to a topic with the same slug).
 */
const v = (base, ...more) => [base, ...more];

export const WORDS = [
  { slug: "love", word: "love", forms: v("love", "loves", "loved", "loving", "loveth", "lovest", "lovedst"), web: v("love", "loves", "loved", "loving"), exclude: v("loving kindness"), note: "The World English Bible's loving kindness, its word for the Hebrew hesed, is left out of these counts: the KJV prints it as one word, lovingkindness, so counting it would compare different things." },
  { slug: "god", word: "God", kind: "name", cases: true, forms: v("god", "gods", "god's") },
  { slug: "jesus", word: "Jesus", kind: "name", forms: v("jesus") },
  { slug: "christ", word: "Christ", kind: "name", forms: v("christ", "christ's", "christs") },
  { slug: "lord", word: "Lord", kind: "name", cases: true, forms: v("lord", "lords", "lord's"), web: v("lord", "lords", "lord's", "yahweh", "yahweh's"), note: "Where the KJV prints LORD in capitals it stands for God's personal name (YHWH). The World English Bible writes that name as Yahweh, so its Lord count is much lower and Yahweh takes the rest." },
  { slug: "holy-spirit", word: "Holy Spirit", kind: "phrase", forms: v("holy spirit", "holy ghost"), web: v("holy spirit"), topic: "holy-spirit" },
  { slug: "faith", word: "faith", forms: v("faith") },
  { slug: "hope", word: "hope", forms: v("hope", "hopes", "hoped", "hoping", "hopeth") },
  { slug: "grace", word: "grace", forms: v("grace") },
  { slug: "fear", word: "fear", forms: v("fear", "fears", "feared", "fearing", "feareth", "fearest") },
  { slug: "fear-not", word: "fear not", kind: "phrase", exactHeadline: true, forms: v("fear not", "fear ye not", "fear thou not", "be not afraid"), web: v("don't be afraid", "do not be afraid", "don't fear", "do not fear"), topic: "fear", note: "A popular saying claims the Bible says \"fear not\" 365 times, one for every day of the year. This page counts every match of the phrases listed below in the full text." },
  { slug: "heaven", word: "heaven", forms: v("heaven", "heavens", "heaven's") },
  { slug: "hell", word: "hell", forms: v("hell"), web: v("hell", "sheol", "hades", "gehenna", "tartarus"), note: "The KJV uses hell for four different words in the original languages: Sheol (Hebrew), and Hades, Gehenna and Tartarus (Greek). The World English Bible keeps those four words as names, and its column counts each of them." },
  { slug: "money", word: "money", forms: v("money") },
  { slug: "prayer", word: "prayer", forms: v("prayer", "prayers"), note: "Pray and prayed are not counted: the KJV often uses \"I pray thee\" to mean please, so the verb would inflate the count." },
  { slug: "peace", word: "peace", forms: v("peace") },
  { slug: "joy", word: "joy", forms: v("joy", "joys", "joyful") },
  { slug: "satan", word: "Satan", kind: "name", forms: v("satan", "satan's") },
  { slug: "devil", word: "devil", forms: v("devil", "devils", "devil's") },
  { slug: "angels", word: "angel", forms: v("angel", "angels", "angel's", "angels'") },
  { slug: "forgiveness", word: "forgiveness", forms: v("forgiveness", "forgive", "forgiven", "forgave", "forgiveth", "forgiving", "forgivest", "forgives") },
  { slug: "worry", word: "worry", forms: v("worry", "worries", "worried", "worrying"), topic: "worry", related: v("anxiety", "fear", "peace", "trust", "rest"), note: "The World English Bible's usual word for worry is anxious, as in Matthew 6:25, \"don't be anxious for your life\". The KJV says take no thought." },
  { slug: "anxiety", word: "anxious", forms: v("anxious", "anxiety", "anxieties"), topic: "anxiety", related: v("worry", "fear", "peace", "trust", "rest") },
  { slug: "sin", word: "sin", forms: v("sin", "sins", "sinned", "sinneth", "sinning", "sinful") },
  { slug: "israel", word: "Israel", kind: "name", forms: v("israel", "israel's") },
  { slug: "david", word: "David", kind: "name", forms: v("david", "david's") },
  { slug: "moses", word: "Moses", kind: "name", forms: v("moses") },
  { slug: "abraham", word: "Abraham", kind: "name", forms: v("abraham", "abraham's", "abram", "abram's"), note: "Abram is his name until Genesis 17:5, where God renames him Abraham. Both names are counted." },
  { slug: "mary", word: "Mary", kind: "name", forms: v("mary") },
  { slug: "paul", word: "Paul", kind: "name", forms: v("paul", "paul's") },
  { slug: "peter", word: "Peter", kind: "name", forms: v("peter", "peter's") },
  { slug: "seven", word: "seven", forms: v("seven", "seventh", "sevenfold") },
  { slug: "forty", word: "forty", forms: v("forty", "fortieth") },
  { slug: "twelve", word: "twelve", forms: v("twelve", "twelfth") },
  { slug: "wine", word: "wine", forms: v("wine", "wines"), topic: "alcohol" },
  { slug: "drunkenness", word: "drunk", forms: v("drunk", "drunken", "drunkenness", "drunkard", "drunkards"), topic: "alcohol" },
  { slug: "dragon", word: "dragon", forms: v("dragon", "dragons") },
  { slug: "unicorn", word: "unicorn", forms: v("unicorn", "unicorns"), note: "The KJV's unicorn translates the Hebrew re'em. Modern translations, the World English Bible included, render it wild ox." },
  { slug: "woman", word: "woman", forms: v("woman", "women", "woman's", "women's") },
  { slug: "wisdom", word: "wisdom", forms: v("wisdom") },
  { slug: "trust", word: "trust", forms: v("trust", "trusted", "trusteth", "trusting", "trusts", "trustest") },
  { slug: "death", word: "death", forms: v("death", "deaths") },
  { slug: "water", word: "water", forms: v("water", "waters", "watered", "watereth", "watering") },
  { slug: "light", word: "light", forms: v("light", "lights") },
  { slug: "cross", word: "cross", forms: v("cross") },
  { slug: "blood", word: "blood", forms: v("blood", "bloods") },
  { slug: "gold", word: "gold", forms: v("gold", "golden") },
  { slug: "amen", word: "amen", forms: v("amen") },
  { slug: "hallelujah", word: "hallelujah", kind: "phrase", exactHeadline: true, kjvLabel: "Alleluia", forms: v("alleluia", "praise ye the lord", "hallelujah"), web: v("hallelujah", "praise yah"), note: "Hallelujah is Hebrew for praise Yah. The KJV prints it as Alleluia only in Revelation 19 and translates it as praise ye the LORD everywhere else. The World English Bible writes Hallelujah in Revelation and Praise Yah in the Psalms." },
  { slug: "mercy", word: "mercy", forms: v("mercy", "mercies", "merciful") },
  { slug: "glory", word: "glory", forms: v("glory", "glorious", "glorify", "glorified") },
  { slug: "truth", word: "truth", forms: v("truth", "truths") },
  { slug: "righteousness", word: "righteousness", forms: v("righteousness") },
  { slug: "salvation", word: "salvation", forms: v("salvation") },
  { slug: "repent", word: "repent", forms: v("repent", "repentance", "repented", "repenteth", "repenting"), topic: "repentance" },
  { slug: "kingdom-of-god", word: "kingdom of God", kind: "phrase", forms: v("kingdom of god"), web: v("god's kingdom", "kingdom of god"), note: "The World English Bible words it God's Kingdom, so both phrasings are counted for it." },
  { slug: "kingdom-of-heaven", word: "kingdom of heaven", kind: "phrase", forms: v("kingdom of heaven") },
  { slug: "eternal-life", word: "eternal life", kind: "phrase", forms: v("eternal life", "everlasting life", "life eternal"), web: v("eternal life", "everlasting life"), topic: "eternal-life" },
  { slug: "son-of-man", word: "Son of Man", kind: "phrase", forms: v("son of man") },
  { slug: "rest", word: "rest", forms: v("rest", "rested", "resteth", "resting"), note: "Rest also means \"the remainder\" (the rest of the people). Every use is counted." },
  { slug: "patience", word: "patience", forms: v("patience", "patient", "patiently") },
  { slug: "obey", word: "obey", forms: v("obey", "obeyed", "obeyeth", "obeying", "obedience", "obedient"), topic: "obedience" },
  { slug: "worship", word: "worship", forms: v("worship", "worshipped", "worshiped", "worshipping", "worshiping", "worshippeth", "worshippers", "worshipers") },
  { slug: "praise", word: "praise", forms: v("praise", "praises", "praised", "praising") },
  { slug: "sabbath", word: "sabbath", forms: v("sabbath", "sabbaths") },
  { slug: "tithe", word: "tithe", forms: v("tithe", "tithes", "tithing"), topic: "tithing" },
  { slug: "marriage", word: "marriage", forms: v("marriage", "marry", "married", "marrieth", "marrying") },
  { slug: "divorce", word: "divorce", forms: v("divorce", "divorced", "divorcement", "divorces") },
  { slug: "healing", word: "healing", forms: v("healing", "heal", "healed", "healeth", "heals") },
  { slug: "strength", word: "strength", forms: v("strength", "strengthen", "strengthened", "strengtheneth") },
  { slug: "courage", word: "courage", forms: v("courage", "courageous", "courageously") },
  { slug: "pride", word: "pride", forms: v("pride", "proud") },
  { slug: "humility", word: "humility", forms: v("humility", "humble", "humbled", "humbleth", "humbly") },
  { slug: "sheep", word: "sheep", forms: v("sheep") },
  { slug: "lamb", word: "lamb", forms: v("lamb", "lambs", "lamb's") },
  { slug: "thankful", word: "thankful", forms: v("thankful", "thanks", "thank", "thanked", "thanksgiving", "thankfulness"), topic: "gratitude" },
  { slug: "rejoice", word: "rejoice", forms: v("rejoice", "rejoiced", "rejoiceth", "rejoicing", "rejoices") },
  { slug: "blessed", word: "blessed", forms: v("blessed", "bless", "blessing", "blessings", "blesseth", "blesses"), topic: "blessings" },
  { slug: "jerusalem", word: "Jerusalem", kind: "name", forms: v("jerusalem") },
  { slug: "egypt", word: "Egypt", kind: "name", forms: v("egypt") },
  { slug: "church", word: "church", forms: v("church", "churches"), note: "The World English Bible translates the Greek word ekklesia as assembly, so the word church never appears in it." },
  { slug: "fasting", word: "fasting", forms: v("fasting", "fasted", "fastings") },
  { slug: "remember", word: "remember", forms: v("remember", "remembered", "remembereth", "remembrance", "remembering") },
  { slug: "dreams", word: "dream", forms: v("dream", "dreams", "dreamed", "dreamer", "dreamers") },
  { slug: "music", word: "music", forms: v("music", "musick", "musical", "musician", "musicians") },
  { slug: "dance", word: "dance", forms: v("dance", "danced", "dances", "dancing") },
  { slug: "dog", word: "dog", forms: v("dog", "dogs", "dog's") },
  { slug: "lion", word: "lion", forms: v("lion", "lions", "lion's") },
  { slug: "children", word: "children", forms: v("children", "child", "child's", "children's") },
  { slug: "mother", word: "mother", forms: v("mother", "mothers", "mother's"), topic: "mothers" },
  { slug: "father", word: "father", forms: v("father", "fathers", "father's"), topic: "fathers" },
  { slug: "friend", word: "friend", forms: v("friend", "friends", "friend's"), topic: "friendship" },
  { slug: "heart", word: "heart", forms: v("heart", "hearts", "heart's") },
  { slug: "holy", word: "holy", forms: v("holy") },
  { slug: "kindness", word: "kindness", forms: v("kindness", "lovingkindness", "kindly") },
  { slug: "comfort", word: "comfort", forms: v("comfort", "comforted", "comforter", "comforteth", "comforts", "comforting") },
  { slug: "spirit", word: "spirit", forms: v("spirit", "spirits") },
  { slug: "covenant", word: "covenant", forms: v("covenant", "covenants") },
  { slug: "miracle", word: "miracle", forms: v("miracle", "miracles") },
  { slug: "prophet", word: "prophet", forms: v("prophet", "prophets", "prophet's") },
  { slug: "baptism", word: "baptism", forms: v("baptism", "baptize", "baptized", "baptizing", "baptizeth") },
  { slug: "resurrection", word: "resurrection", forms: v("resurrection") },
  { slug: "grief", word: "grief", forms: v("grief", "griefs", "sorrow", "sorrows") },
  { slug: "anger", word: "anger", forms: v("anger", "angry") },
  { slug: "sleep", word: "sleep", forms: v("sleep", "slept", "sleepeth", "sleeping") },
  { slug: "debt", word: "debt", forms: v("debt", "debts", "debtor", "debtors") },
  { slug: "tattoo", word: "tattoo", forms: v("tattoo", "tattoos"), topic: "tattoos", note: "Leviticus 19:28 is the only verse usually read as being about tattoos. The KJV words it \"nor print any marks upon you\"; the World English Bible says \"nor tattoo any marks on you\"." },
];
