/**
 * Words and phrases with a /words/<slug> page. `forms` are matched in the KJV (case-insensitive, whole words);
 * `web` overrides them for the World English Bible when its wording differs. The first form is the headline word.
 * kind: word (headline = the exact first form) | phrase (headline = all forms together) | name.
 * cases: show the capitalization split (God / god / GOD).
 * topic: the /verses/<topic> page this word belongs with (defaults to a topic with the same slug).
 */
const v = (base, ...more) => [base, ...more];

const CORE = [
  { slug: "love", word: "love", forms: v("love", "loves", "loved", "loving", "loveth", "lovest", "lovedst"), web: v("love", "loves", "loved", "loving"), exclude: v("loving kindness"), note: "The World English Bible's loving kindness, its word for the Hebrew hesed, is left out of these counts: the KJV prints it as one word, lovingkindness, so counting it would compare different things." },
  { slug: "god", word: "God", kind: "name", cases: true, forms: v("god", "gods", "god's") },
  { slug: "jesus", word: "Jesus", kind: "name", forms: v("jesus") },
  { slug: "christ", word: "Christ", kind: "name", forms: v("christ", "christ's", "christs") },
  { slug: "lord", word: "Lord", kind: "name", cases: true, forms: v("lord", "lords", "lord's"), web: v("lord", "lords", "lord's", "yahweh", "yahweh's"), note: "Where the KJV prints LORD in capitals it stands for God's personal name (YHWH). The World English Bible writes that name as Yahweh, so its Lord count is much lower and Yahweh takes the rest." },
  { slug: "holy-spirit", word: "Holy Spirit", kind: "phrase", forms: v("holy spirit", "holy ghost"), web: v("holy spirit"), topic: "holy-spirit" },
  { slug: "faith", word: "faith", forms: v("faith") },
  { slug: "hope", word: "hope", forms: v("hope", "hopes", "hoped", "hoping", "hopeth") },
  { slug: "grace", word: "grace", forms: v("grace") },
  { slug: "fear", word: "fear", forms: v("fear", "fears", "feared", "fearing", "feareth", "fearest") },
  { slug: "fear-not", word: "fear not", kind: "phrase", exactHeadline: true, forms: v("fear not", "fear ye not", "fear thou not", "be not afraid"), web: v("don't be afraid", "do not be afraid", "don't fear", "do not fear"), topic: "fear", note: "A popular saying claims the Bible says \"fear not\" 365 times, one for every day of the year. This page counts every match of the phrases listed below in the full text." },
  { slug: "heaven", word: "heaven", forms: v("heaven", "heavens", "heaven's") },
  { slug: "hell", word: "hell", forms: v("hell"), web: v("hell", "sheol", "hades", "gehenna", "tartarus"), note: "The KJV uses hell for four different words in the original languages: Sheol (Hebrew), and Hades, Gehenna and Tartarus (Greek). The World English Bible keeps those four words as names, and its column counts each of them." },
  { slug: "money", word: "money", forms: v("money") },
  { slug: "prayer", word: "prayer", forms: v("prayer", "prayers"), note: "Pray and prayed are not counted: the KJV often uses \"I pray thee\" to mean please, so the verb would inflate the count." },
  { slug: "peace", word: "peace", forms: v("peace") },
  { slug: "joy", word: "joy", forms: v("joy", "joys", "joyful") },
  { slug: "satan", word: "Satan", kind: "name", forms: v("satan", "satan's") },
  { slug: "devil", word: "devil", forms: v("devil", "devils", "devil's") },
  { slug: "angels", word: "angel", forms: v("angel", "angels", "angel's", "angels'") },
  { slug: "forgiveness", word: "forgiveness", forms: v("forgiveness", "forgive", "forgiven", "forgave", "forgiveth", "forgiving", "forgivest", "forgives") },
  { slug: "worry", word: "worry", forms: v("worry", "worries", "worried", "worrying"), topic: "worry", related: v("anxiety", "fear", "peace", "trust", "rest"), note: "The World English Bible's usual word for worry is anxious, as in Matthew 6:25, \"don't be anxious for your life\". The KJV says take no thought." },
  { slug: "anxiety", word: "anxious", forms: v("anxious", "anxiety", "anxieties"), topic: "anxiety", related: v("worry", "fear", "peace", "trust", "rest") },
  { slug: "sin", word: "sin", forms: v("sin", "sins", "sinned", "sinneth", "sinning", "sinful") },
  { slug: "israel", word: "Israel", kind: "name", forms: v("israel", "israel's") },
  { slug: "david", word: "David", kind: "name", forms: v("david", "david's") },
  { slug: "moses", word: "Moses", kind: "name", forms: v("moses") },
  { slug: "abraham", word: "Abraham", kind: "name", forms: v("abraham", "abraham's", "abram", "abram's"), note: "Abram is his name until Genesis 17:5, where God renames him Abraham. Both names are counted." },
  { slug: "mary", word: "Mary", kind: "name", forms: v("mary") },
  { slug: "paul", word: "Paul", kind: "name", forms: v("paul", "paul's") },
  { slug: "peter", word: "Peter", kind: "name", forms: v("peter", "peter's") },
  { slug: "seven", word: "seven", forms: v("seven", "seventh", "sevenfold") },
  { slug: "forty", word: "forty", forms: v("forty", "fortieth") },
  { slug: "twelve", word: "twelve", forms: v("twelve", "twelfth") },
  { slug: "wine", word: "wine", forms: v("wine", "wines"), topic: "alcohol" },
  { slug: "drunkenness", word: "drunk", forms: v("drunk", "drunken", "drunkenness", "drunkard", "drunkards"), topic: "alcohol" },
  { slug: "dragon", word: "dragon", forms: v("dragon", "dragons") },
  { slug: "unicorn", word: "unicorn", forms: v("unicorn", "unicorns"), note: "The KJV's unicorn translates the Hebrew re'em. Modern translations, the World English Bible included, render it wild ox." },
  { slug: "woman", word: "woman", forms: v("woman", "women", "woman's", "women's") },
  { slug: "wisdom", word: "wisdom", forms: v("wisdom") },
  { slug: "trust", word: "trust", forms: v("trust", "trusted", "trusteth", "trusting", "trusts", "trustest") },
  { slug: "death", word: "death", forms: v("death", "deaths") },
  { slug: "water", word: "water", forms: v("water", "waters", "watered", "watereth", "watering") },
  { slug: "light", word: "light", forms: v("light", "lights") },
  { slug: "cross", word: "cross", forms: v("cross") },
  { slug: "blood", word: "blood", forms: v("blood", "bloods") },
  { slug: "gold", word: "gold", forms: v("gold", "golden") },
  { slug: "amen", word: "amen", forms: v("amen") },
  { slug: "hallelujah", word: "hallelujah", kind: "phrase", exactHeadline: true, kjvLabel: "Alleluia", forms: v("alleluia", "praise ye the lord", "hallelujah"), web: v("hallelujah", "praise yah"), note: "Hallelujah is Hebrew for praise Yah. The KJV prints it as Alleluia only in Revelation 19 and translates it as praise ye the LORD everywhere else. The World English Bible writes Hallelujah in Revelation and Praise Yah in the Psalms." },
  { slug: "mercy", word: "mercy", forms: v("mercy", "mercies", "merciful") },
  { slug: "glory", word: "glory", forms: v("glory", "glorious", "glorify", "glorified") },
  { slug: "truth", word: "truth", forms: v("truth", "truths") },
  { slug: "righteousness", word: "righteousness", forms: v("righteousness") },
  { slug: "salvation", word: "salvation", forms: v("salvation") },
  { slug: "repent", word: "repent", forms: v("repent", "repentance", "repented", "repenteth", "repenting"), topic: "repentance" },
  { slug: "kingdom-of-god", word: "kingdom of God", kind: "phrase", forms: v("kingdom of god"), web: v("god's kingdom", "kingdom of god"), note: "The World English Bible words it God's Kingdom, so both phrasings are counted for it." },
  { slug: "kingdom-of-heaven", word: "kingdom of heaven", kind: "phrase", forms: v("kingdom of heaven") },
  { slug: "eternal-life", word: "eternal life", kind: "phrase", forms: v("eternal life", "everlasting life", "life eternal"), web: v("eternal life", "everlasting life"), topic: "eternal-life" },
  { slug: "son-of-man", word: "Son of Man", kind: "phrase", forms: v("son of man") },
  { slug: "rest", word: "rest", forms: v("rest", "rested", "resteth", "resting"), note: "Rest also means \"the remainder\" (the rest of the people). Every use is counted." },
  { slug: "patience", word: "patience", forms: v("patience", "patient", "patiently") },
  { slug: "obey", word: "obey", forms: v("obey", "obeyed", "obeyeth", "obeying", "obedience", "obedient"), topic: "obedience" },
  { slug: "worship", word: "worship", forms: v("worship", "worshipped", "worshiped", "worshipping", "worshiping", "worshippeth", "worshippers", "worshipers") },
  { slug: "praise", word: "praise", forms: v("praise", "praises", "praised", "praising") },
  { slug: "sabbath", word: "sabbath", forms: v("sabbath", "sabbaths") },
  { slug: "tithe", word: "tithe", forms: v("tithe", "tithes", "tithing"), topic: "tithing" },
  { slug: "marriage", word: "marriage", forms: v("marriage", "marry", "married", "marrieth", "marrying") },
  { slug: "divorce", word: "divorce", forms: v("divorce", "divorced", "divorcement", "divorces") },
  { slug: "healing", word: "healing", forms: v("healing", "heal", "healed", "healeth", "heals") },
  { slug: "strength", word: "strength", forms: v("strength", "strengthen", "strengthened", "strengtheneth") },
  { slug: "courage", word: "courage", forms: v("courage", "courageous", "courageously") },
  { slug: "pride", word: "pride", forms: v("pride", "proud") },
  { slug: "humility", word: "humility", forms: v("humility", "humble", "humbled", "humbleth", "humbly") },
  { slug: "sheep", word: "sheep", forms: v("sheep") },
  { slug: "lamb", word: "lamb", forms: v("lamb", "lambs", "lamb's") },
  { slug: "thankful", word: "thankful", forms: v("thankful", "thanks", "thank", "thanked", "thanksgiving", "thankfulness"), topic: "gratitude" },
  { slug: "rejoice", word: "rejoice", forms: v("rejoice", "rejoiced", "rejoiceth", "rejoicing", "rejoices") },
  { slug: "blessed", word: "blessed", forms: v("blessed", "bless", "blessing", "blessings", "blesseth", "blesses"), topic: "blessings" },
  { slug: "jerusalem", word: "Jerusalem", kind: "name", forms: v("jerusalem") },
  { slug: "egypt", word: "Egypt", kind: "name", forms: v("egypt") },
  { slug: "church", word: "church", forms: v("church", "churches"), note: "The World English Bible translates the Greek word ekklesia as assembly, so the word church never appears in it." },
  { slug: "fasting", word: "fasting", forms: v("fasting", "fasted", "fastings") },
  { slug: "remember", word: "remember", forms: v("remember", "remembered", "remembereth", "remembrance", "remembering") },
  { slug: "dreams", word: "dream", forms: v("dream", "dreams", "dreamed", "dreamer", "dreamers") },
  { slug: "music", word: "music", forms: v("music", "musick", "musical", "musician", "musicians") },
  { slug: "dance", word: "dance", forms: v("dance", "danced", "dances", "dancing") },
  { slug: "dog", word: "dog", forms: v("dog", "dogs", "dog's") },
  { slug: "lion", word: "lion", forms: v("lion", "lions", "lion's") },
  { slug: "children", word: "children", forms: v("children", "child", "child's", "children's") },
  { slug: "mother", word: "mother", forms: v("mother", "mothers", "mother's"), topic: "mothers" },
  { slug: "father", word: "father", forms: v("father", "fathers", "father's"), topic: "fathers" },
  { slug: "friend", word: "friend", forms: v("friend", "friends", "friend's"), topic: "friendship" },
  { slug: "heart", word: "heart", forms: v("heart", "hearts", "heart's") },
  { slug: "holy", word: "holy", forms: v("holy") },
  { slug: "kindness", word: "kindness", forms: v("kindness", "lovingkindness", "kindly") },
  { slug: "comfort", word: "comfort", forms: v("comfort", "comforted", "comforter", "comforteth", "comforts", "comforting") },
  { slug: "spirit", word: "spirit", forms: v("spirit", "spirits") },
  { slug: "covenant", word: "covenant", forms: v("covenant", "covenants") },
  { slug: "miracle", word: "miracle", forms: v("miracle", "miracles") },
  { slug: "prophet", word: "prophet", forms: v("prophet", "prophets", "prophet's") },
  { slug: "baptism", word: "baptism", forms: v("baptism", "baptize", "baptized", "baptizing", "baptizeth") },
  { slug: "resurrection", word: "resurrection", forms: v("resurrection") },
  { slug: "grief", word: "grief", forms: v("grief", "griefs", "sorrow", "sorrows") },
  { slug: "anger", word: "anger", forms: v("anger", "angry") },
  { slug: "sleep", word: "sleep", forms: v("sleep", "slept", "sleepeth", "sleeping") },
  { slug: "debt", word: "debt", forms: v("debt", "debts", "debtor", "debtors") },
  { slug: "tattoo", word: "tattoo", forms: v("tattoo", "tattoos"), topic: "tattoos", note: "Leviticus 19:28 is the only verse usually read as being about tattoos. The KJV words it \"nor print any marks upon you\"; the World English Bible says \"nor tattoo any marks on you\"." },
];

// ---- 2026-10-05 extension: the second wave of the entity template (same counting rules, same page) ----
const nm = (slug, word, forms, extra = {}) => ({ slug, word, kind: "name", forms, ...extra });
const wd = (slug, word, forms, extra = {}) => ({ slug, word, forms, ...extra });
const ph = (slug, word, forms, extra = {}) => ({ slug, word, kind: "phrase", forms, ...extra });
const SEV = "Several men share this name, and every one is counted.";

const MORE = [
  // people
  nm("noah", "Noah", v("noah", "noah's", "noe"), { web: v("noah", "noah's"), note: "The KJV spells the name Noe in the New Testament (Matthew 24:37, Luke 3:36 and 17:26-27, Hebrews 11:7). Both spellings are counted." }),
  nm("adam", "Adam", v("adam", "adam's")),
  nm("eve", "Eve", v("eve")),
  nm("isaac", "Isaac", v("isaac", "isaac's")),
  nm("jacob", "Jacob", v("jacob", "jacob's"), { note: "Jacob is also called Israel. Only the name Jacob is counted here; the Israel page counts that name." }),
  nm("joseph", "Joseph", v("joseph", "joseph's"), { note: SEV }),
  nm("solomon", "Solomon", v("solomon", "solomon's")),
  nm("aaron", "Aaron", v("aaron", "aaron's")),
  nm("joshua", "Joshua", v("joshua", "joshua's"), { note: "The KJV prints Jesus for Joshua in Acts 7:45 and Hebrews 4:8, so those two verses are not counted." }),
  nm("samuel", "Samuel", v("samuel", "samuel's")),
  nm("saul", "Saul", v("saul", "saul's"), { note: "Saul is the first king of Israel and also the Hebrew name of the apostle Paul before Acts 13:9. Every use is counted." }),
  nm("elijah", "Elijah", v("elijah", "elijah's", "elias"), { web: v("elijah", "elijah's"), note: "The KJV spells the name Elias in the New Testament. Both spellings are counted." }),
  nm("elisha", "Elisha", v("elisha", "elisha's", "eliseus"), { web: v("elisha", "elisha's"), note: "The KJV spells the name Eliseus in Luke 4:27. Both spellings are counted." }),
  nm("daniel", "Daniel", v("daniel", "daniel's"), { note: "Daniel is also the name of a son of David and a priest in Ezra. Every use is counted." }),
  nm("john", "John", v("john", "john's"), { note: "John the Baptist, the apostle, and John Mark all share the name. Every use is counted." }),
  nm("james", "James", v("james", "james'"), { note: "At least two apostles are named James, and so is the brother of Jesus. Every use is counted." }),
  nm("judas", "Judas", v("judas", "judas'"), { note: "Judas Iscariot, the apostle Judas son of James, and Judas of Damascus are all counted." }),
  nm("martha", "Martha", v("martha")),
  nm("lazarus", "Lazarus", v("lazarus"), { note: "Two men are named Lazarus: the brother of Mary and Martha in John 11-12, and the beggar in Jesus' story in Luke 16. Both are counted." }),
  nm("gabriel", "Gabriel", v("gabriel")),
  nm("michael", "Michael", v("michael"), { note: "The archangel is named in Daniel, Jude 9 and Revelation 12:7. Michael is also the name of several men in Numbers and Chronicles, and all of them are counted." }),
  nm("stephen", "Stephen", v("stephen", "stephen's")),
  nm("timothy", "Timothy", v("timothy", "timotheus"), { web: v("timothy"), note: "The KJV spells the name Timotheus in Acts 16-20, Romans 16:21 and Hebrews 13:23. Both spellings are counted." }),
  nm("thomas", "Thomas", v("thomas")),
  nm("barnabas", "Barnabas", v("barnabas")),
  nm("silas", "Silas", v("silas")),
  nm("ruth", "Ruth", v("ruth")),
  nm("esther", "Esther", v("esther")),
  nm("job", "Job", v("job", "job's")),
  nm("sarah", "Sarah", v("sarah", "sarah's", "sarai", "sarai's"), { note: "Sarah is called Sarai until God renames her in Genesis 17:15. Both names are counted." }),
  nm("rebekah", "Rebekah", v("rebekah", "rebekah's", "rebecca"), { web: v("rebekah", "rebekah's"), note: "The KJV spells the name Rebecca in Romans 9:10. Both spellings are counted." }),
  nm("rachel", "Rachel", v("rachel", "rachel's")),
  nm("leah", "Leah", v("leah", "leah's")),
  nm("samson", "Samson", v("samson", "samson's")),
  nm("goliath", "Goliath", v("goliath", "goliath's")),
  nm("gideon", "Gideon", v("gideon", "gideon's")),
  nm("jonah", "Jonah", v("jonah", "jonas"), { web: v("jonah"), note: "The KJV spells the name Jonas in Matthew 12 and 16, Luke 11 and John 1:42 (where Jonas is Peter's father). Both spellings are counted." }),
  nm("isaiah", "Isaiah", v("isaiah", "isaiah's", "esaias", "esaias'"), { web: v("isaiah", "isaiah's"), note: "The KJV spells the name Esaias in the New Testament. Both spellings are counted." }),
  nm("jeremiah", "Jeremiah", v("jeremiah", "jeremiah's", "jeremias", "jeremy"), { web: v("jeremiah", "jeremiah's"), note: "The KJV spells the name Jeremias in Matthew 16:14 and Jeremy in Matthew 2:17 and 27:9. Every spelling is counted, and so is every man of that name." }),
  nm("nebuchadnezzar", "Nebuchadnezzar", v("nebuchadnezzar", "nebuchadnezzar's", "nebuchadrezzar", "nebuchadrezzar's"), { note: "The KJV uses both spellings, Nebuchadnezzar in Daniel and Nebuchadrezzar in Jeremiah and Ezekiel. Both are counted." }),
  nm("pharaoh", "Pharaoh", v("pharaoh", "pharaoh's"), { note: "Pharaoh is a title, not a name, and the Bible uses it for several different kings of Egypt. Every use is counted." }),
  nm("herod", "Herod", v("herod", "herod's"), { note: "The New Testament names several rulers Herod: Herod the Great, Herod Antipas and Herod Agrippa. Every use is counted." }),
  nm("pilate", "Pilate", v("pilate", "pilate's")),
  nm("cain", "Cain", v("cain", "cain's")),
  nm("ishmael", "Ishmael", v("ishmael", "ishmael's"), { note: SEV }),
  nm("esau", "Esau", v("esau", "esau's")),
  nm("judah", "Judah", v("judah", "judah's", "juda"), { web: v("judah", "judah's"), note: "Judah is a son of Jacob, the tribe named for him and the southern kingdom. The KJV spells the name Juda in the New Testament. Every use is counted." }),
  // places
  nm("babylon", "Babylon", v("babylon", "babylon's")),
  nm("bethlehem", "Bethlehem", v("bethlehem")),
  nm("nazareth", "Nazareth", v("nazareth")),
  nm("galilee", "Galilee", v("galilee")),
  nm("jordan", "Jordan", v("jordan")),
  nm("sinai", "Sinai", v("sinai")),
  nm("sodom", "Sodom", v("sodom", "sodom's")),
  nm("gomorrah", "Gomorrah", v("gomorrah", "gomorrha"), { web: v("gomorrah"), note: "The KJV spells the name Gomorrha in the New Testament. Both spellings are counted." }),
  nm("eden", "Eden", v("eden", "eden's"), { note: "Eden also names a Levite and a town in a few verses; every use is counted." }),
  nm("zion", "Zion", v("zion", "zion's")),
  nm("canaan", "Canaan", v("canaan")),
  nm("damascus", "Damascus", v("damascus")),
  nm("jericho", "Jericho", v("jericho")),
  nm("samaria", "Samaria", v("samaria")),
  nm("nineveh", "Nineveh", v("nineveh")),
  // things, animals, objects
  wd("serpent", "serpent", v("serpent", "serpents", "serpent's")),
  wd("bread", "bread", v("bread", "breads")),
  wd("honey", "honey", v("honey", "honeycomb")),
  wd("milk", "milk", v("milk")),
  wd("oil", "oil", v("oil", "oils")),
  wd("salt", "salt", v("salt")),
  wd("fire", "fire", v("fire", "fires")),
  wd("sword", "sword", v("sword", "swords")),
  wd("king", "king", v("king", "kings", "king's")),
  wd("priest", "priest", v("priest", "priests", "priest's")),
  wd("wife", "wife", v("wife", "wives", "wife's")),
  wd("wicked", "wicked", v("wicked", "wickedness")),
  wd("mountain", "mountain", v("mountain", "mountains")),
  wd("tree", "tree", v("tree", "trees")),
  wd("vine", "vine", v("vine", "vines", "vineyard", "vineyards")),
  wd("eagle", "eagle", v("eagle", "eagles")),
  wd("horse", "horse", v("horse", "horses")),
  wd("camel", "camel", v("camel", "camels")),
  wd("fish", "fish", v("fish", "fishes")),
  wd("wolf", "wolf", v("wolf", "wolves")),
  wd("sparrow", "sparrow", v("sparrow", "sparrows")),
  wd("goat", "goat", v("goat", "goats")),
  wd("dove", "dove", v("dove", "doves")),
  wd("locust", "locust", v("locust", "locusts")),
  wd("soul", "soul", v("soul", "souls", "soul's")),
  wd("bride", "bride", v("bride")),
  wd("widow", "widow", v("widow", "widows"), { topic: "widows" }),
  wd("poor", "poor", v("poor")),
  wd("riches", "riches", v("riches"), { topic: "wealth" }),
  wd("sun", "sun", v("sun")),
  wd("moon", "moon", v("moon", "moons")),
  wd("wilderness", "wilderness", v("wilderness")),
  wd("crown", "crown", v("crown", "crowns", "crowned")),
  wd("throne", "throne", v("throne", "thrones")),
  wd("altar", "altar", v("altar", "altars")),
  wd("temple", "temple", v("temple", "temples")),
  wd("tabernacle", "tabernacle", v("tabernacle", "tabernacles")),
  wd("ark", "ark", v("ark")),
  wd("sacrifice", "sacrifice", v("sacrifice", "sacrifices", "sacrificed", "sacrificing")),
  wd("incense", "incense", v("incense")),
  wd("idol", "idol", v("idol", "idols"), { topic: "idolatry" }),
  wd("apostle", "apostle", v("apostle", "apostles")),
  wd("disciple", "disciple", v("disciple", "disciples"), { topic: "discipleship" }),
  wd("elder", "elder", v("elder", "elders"), { note: "Elder is also a comparative (the elder brother, the elder shall serve the younger). Every use is counted." }),
  wd("gospel", "gospel", v("gospel"), { note: "The World English Bible translates the Greek word euangelion as good news, so the word gospel never appears in it." , topic: "evangelism" }),
  wd("parable", "parable", v("parable", "parables")),
  wd("demon", "demon", v("demon", "demons"), { note: "The KJV does not use the word demon. It translates the Greek word for demons as devils, which is why the Devil page counts a different thing. The World English Bible says demons." , topic: "demons" }),
  wd("judgment", "judgment", v("judgment", "judgments")),
  wd("wrath", "wrath", v("wrath")),
  wd("vengeance", "vengeance", v("vengeance"), { topic: "revenge" }),
  wd("envy", "envy", v("envy", "envied", "envieth", "envying", "envyings"), { topic: "jealousy" }),
  wd("lust", "lust", v("lust", "lusts", "lusted", "lusteth", "lusting")),
  wd("hate", "hate", v("hate", "hated", "hateth", "hatred", "hates")),
  wd("compassion", "compassion", v("compassion", "compassions")),
  wd("goodness", "goodness", v("goodness")),
  wd("faithful", "faithful", v("faithful", "faithfulness"), { topic: "faithfulness" }),
  wd("righteous", "righteous", v("righteous")),
  wd("sinner", "sinner", v("sinner", "sinners")),
  wd("saint", "saint", v("saint", "saints")),
  wd("redemption", "redemption", v("redemption", "redeem", "redeemed", "redeemer", "redeemeth", "redeems")),
  wd("atonement", "atonement", v("atonement")),
  wd("gentiles", "Gentiles", v("gentiles", "gentile")),
  wd("giants", "giant", v("giant", "giants"), { note: "The KJV prints giants for the Hebrew Rephaim and Nephilim and for the sons of Anak. The World English Bible keeps Nephilim and Rephaim as names." }),
  wd("easter", "Easter", v("easter"), { note: "Easter appears once in the KJV, in Acts 12:4, where the Greek word is pascha, the Passover. Every other English Bible, the World English Bible included, translates it Passover." }),
  wd("selah", "Selah", v("selah")),
  wd("behold", "behold", v("behold")),
  wd("verily", "verily", v("verily"), { web: v("most certainly"), note: "The World English Bible has no verily. Its wording for the same Greek word, most certainly, is counted in the World English Bible column." }),
  wd("manna", "manna", v("manna")),
  wd("passover", "Passover", v("passover", "passovers")),
  nm("jehovah", "Jehovah", v("jehovah"), { note: "The KJV prints Jehovah only a few times and prints LORD in capitals for God's name everywhere else. The World English Bible writes Yahweh. See the Yahweh page for that count." }),
  nm("yahweh", "Yahweh", v("yahweh", "yahweh's"), { note: "The King James Version never prints Yahweh. Where the Hebrew has God's personal name it prints LORD in capitals (and Jehovah in a few verses). The World English Bible prints Yahweh, so its column is the count." }),
  wd("leviathan", "Leviathan", v("leviathan")),
  nm("antichrist", "Antichrist", v("antichrist", "antichrists")),
  // phrases
  ph("thus-saith-the-lord", "thus saith the LORD", v("thus saith the lord"), { web: v("thus says the lord", "thus says yahweh"), note: "The World English Bible words the same phrase \"thus says the Lord\" or \"thus says Yahweh\", and both are counted in its column." }),
  ph("verily-verily", "verily, verily", v("verily verily"), { exactHeadline: true, note: "All of these are in John's Gospel and all are Jesus speaking. The World English Bible does not double the word: it renders each one \"most certainly\", so its count for the doubled phrase is zero." }),
  ph("born-again", "born again", v("born again"), { exactHeadline: true, web: v("born again", "born anew"), note: "The World English Bible has \"born anew\" where the KJV has \"born again\" in John 3." }),
  ph("son-of-god", "Son of God", v("son of god", "sons of god"), { web: v("son of god", "sons of god") }),
  ph("alpha-and-omega", "Alpha and Omega", v("alpha and omega"), { web: v("alpha and the omega"), note: "The World English Bible words it \"the Alpha and the Omega\"." }),
  ph("love-one-another", "love one another", v("love one another"), { exactHeadline: true }),
  ph("fear-of-the-lord", "fear of the LORD", v("fear of the lord"), { exactHeadline: true, web: v("fear of yahweh") }),
  ph("forty-days", "forty days", v("forty days"), { exactHeadline: true }),
  ph("jesus-christ", "Jesus Christ", v("jesus christ"), { exactHeadline: true }),
  ph("praise-the-lord", "praise the LORD", v("praise the lord", "praise ye the lord"), { web: v("praise the lord", "praise yah", "praise yahweh"), note: "The King James Version has \"praise ye the LORD\" where the World English Bible has \"praise Yah\" or \"praise Yahweh\"; Hallelujah is the same Hebrew phrase. Both wordings are counted." }),
  ph("666", "666", v("six hundred threescore and six", "six hundred and threescore and six", "six hundred sixty and six"), { web: v("six hundred sixty six"), note: "The KJV writes the number out as six hundred threescore and six (and six hundred sixty and six in Ezra 2:13), and the World English Bible as six hundred sixty-six. Only one of these verses is the number of the beast; the others are weights of gold and a count of people." }),
];

export const WORDS = [...CORE, ...MORE];
